name: Java CI with Gradle
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: access-s3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PW }}
      run:
        aws s3 cp --region ap-northeast-2 ./build/resources/main/static/docs/index.html s3://action-test-minki