name: Java CI with Gradle
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: access-s3
      uses: prewk/s3-cp-action@v2
      with:
        aws_access_key_id: ${{ secrets.AWS_ID }}
        aws_secret_access_key: ${{ secrets.AWS_PW }}
        source: 's3://action-test-minki'
        dest: './build/resources/main/static/docs/index.html'
#      run:
#        aws s3 cp --region ap-northeast-2 ./build/resources/main/static/docs/index.html s3://action-test-minki